// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlT8_VQz7FkT1VCsdeGMHBlThiLcCrFPY',
    appId: '1:651854409807:web:79c7b97ff2c3463c283a3a',
    messagingSenderId: '651854409807',
    projectId: 'kare-355d3',
    authDomain: 'kare-355d3.firebaseapp.com',
    storageBucket: 'kare-355d3.appspot.com',
    measurementId: 'G-DVYQ7J0D9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEYaxz1X8oAhBNUOWNwetkh8wV0Dl8ie0',
    appId: '1:651854409807:android:a5b7f4e86a8ae6eb283a3a',
    messagingSenderId: '651854409807',
    projectId: 'kare-355d3',
    storageBucket: 'kare-355d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRlLL70FMqGQepHvmcckF6VGXRbArN-oI',
    appId: '1:651854409807:ios:93bd667c18480ed1283a3a',
    messagingSenderId: '651854409807',
    projectId: 'kare-355d3',
    storageBucket: 'kare-355d3.appspot.com',
    iosBundleId: 'com.example.secureKare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRlLL70FMqGQepHvmcckF6VGXRbArN-oI',
    appId: '1:651854409807:ios:93bd667c18480ed1283a3a',
    messagingSenderId: '651854409807',
    projectId: 'kare-355d3',
    storageBucket: 'kare-355d3.appspot.com',
    iosBundleId: 'com.example.secureKare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlT8_VQz7FkT1VCsdeGMHBlThiLcCrFPY',
    appId: '1:651854409807:web:d892565c13ac16eb283a3a',
    messagingSenderId: '651854409807',
    projectId: 'kare-355d3',
    authDomain: 'kare-355d3.firebaseapp.com',
    storageBucket: 'kare-355d3.appspot.com',
    measurementId: 'G-39EHF89JXR',
  );
}
